### ISSUE TITLE
the height of the webuipopover changes after second click

### ISSUE THREAD

**Issue by carlosbarahona** [sandywalker/webui-popover#48] opened 2015-03-04 14:08 UTC
I have a webuipopover which loads inline content. Everything works fine in the first click(that opens the popover), but after that click, the height of the popover changes.

Any help would be appreciated.

**Comment by sandywalker** [comment] 2015-03-09 03:51
I follow your description to do the test, but did not find the problem。Do you mean click the trigger element or target content?

**Comment by jaredreich** [comment] 2015-03-25 15:03
I have this issue too, for me both the width and height change.

First click:

![screen shot 2015-03-25 at 9 00 39 am](https://cloud.githubusercontent.com/assets/8563847/6827533/7f2fdf04-d2cd-11e4-8fc9-ec84fa7696b9.png)


Second and subsequent clicks:

![screen shot 2015-03-25 at 9 02 28 am](https://cloud.githubusercontent.com/assets/8563847/6827558/b7a08398-d2cd-11e4-8da7-bf8dc83ec204.png)

**Comment by jaredreich** [comment] 2015-03-26 02:10
@carlosbarahona did you end up finding a fix for this?

**Comment by carlosbarahona** [comment] 2015-03-26 12:01
yes, I solved it using css. I assigned one espcifico id for each popup and associate them a height.

**Comment by jaredreich** [comment] 2015-03-26 15:02
@carlosbarahona I think the real issue is in the js, so I guess you've done a temporary work-around.

@sandywalker looks like the issue is when a popover is created with set width and height options, the actual popover is created with border and padding of 1px each, therefore the content is 2px smaller on each side. Then when the popover is re-opened the content acquires this total size, including the border and padding, so when it reopens it is now 4px higher and 4px wider than the first click.

First click:
![1](https://cloud.githubusercontent.com/assets/8563847/6848913/a9116608-d395-11e4-9131-56cd7732f3d1.png)

Second click:
![2](https://cloud.githubusercontent.com/assets/8563847/6848914/a9130260-d395-11e4-90b0-106c78852046.png)

Also, haven't forked anything yet but I believe the larger height change issue @carlosbarahona was experiencing and commenting on is due to an error in the js where:

Line 166:
```
if (this.options.height!=='auto'){$targetContent.height(this.options.height);}
```
Should be:
```
if (this.options.height!=='auto'){$target.height(this.options.height);}
```

**Comment by sandywalker** [comment] 2015-05-04 07:41
@jaredreich Your suggestion is perfect when the pop content is smaller than the options.height and options.title is set to false, but when the content is too large, it will overflow and cause some scroll problems.
I'll try to find a way to solve the problem.
Thanks

**Comment by Erikmitk** [comment] 2015-06-12 11:04
@sandywalker Could you find an ‘official’ solution? I used the work-around from @jaredreich and that works fine for me, so far. I agree, that there might be problems with overflows and scroll problems. But since I’m setting the height manually anyway, those are not the Popovers fault, but my own if I choose a wrong value? And it actually works the first time the Popover is shown, it’s just that a second calculation goes wrong the way @jaredreich argues.

**Comment by sandywalker** [comment] 2015-12-17 09:15
I've update the plugins so many times , but always forgot this issue. I'm not sure this problem is fixed or not.
 Does any body still who have this problem?

**Closed** 2016-05-14 08:24 UTC
